react select code using static data
Mohitktater/react-select-1 pull request #1
Opened 2024-05-09 07:18 UTC by Mohitktater

Hello 
Please check the code & review it. this having 2 files : 1 src/components/select/Main.js
2. src/components/select/Search.js

2024-05-10 05:55 UTC, Delwalt requested changes

2024-05-10 05:55 UTC, Delwalt commented on public/index.html
> +    <!--
always remove unnecessary comments from code

2024-05-10 05:55 UTC, Delwalt commented on src/App.css
Why adding this file if its empty ?

2024-05-10 05:55 UTC, Delwalt commented on src/App.js
> +function App() {
no need to implement routing we are just creating select component

2024-05-10 05:55 UTC, Delwalt commented on src/App.js
> +import Main from "./components/select/Main.js";
instead of creating Main.js file general convention is to create index.js file so that you can import it like this 

`import Select from "./components/select";`

Also Import name should tell what you are importing here ideal name would be Select because thats is what you importing.

2024-05-10 05:55 UTC, Delwalt commented on src/App.test.js
> +import { render, screen } from '@testing-library/react';
We will learn later how to write the test cases so currently ignoring this file.

2024-05-10 05:55 UTC, Delwalt commented on src/components/.DS_Store
.DS_Store file should be added to gitignore as it is not relevant for the project.

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Main.js
as commented before you can have following folder file structure - `components/Select/index.js`  makes importing the component really easy.

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Main.js
> +  const [selectedOption, setSelectedOption] = useState([]);
why this state is initialized using array ? selectedOption will be an object right ? also initially it should be initialized null since in start we dont have any value selected right ?

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Main.js
> +    console.log(dataSubmited);
should remove debugging console before commiting

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Main.js
> +  const handleSubmit = async (e) => {
why this function is needed ?

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Search.js
> +  const [filteredOptions, setFilteredOptions] = useState([options]);
options is already an array we why are we doing this `[options]` in useState ?

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Search.js
> +export const SearchableSelect = ({ options, onSelectFromList }) => {
prop `onSelectFromList` can have more simpler name like `onSelect`

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Search.js
> +  }, [options]);
why did you add this useEffect ?

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Search.js
> +    setIsListVisiable((prevState) => (prevState === true ? false : true));
This can be simplified like this

```suggestion
    setIsListVisiable((prevState) => !prevState);
```

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/Search.js
> +              <li key={index} onClick={() => handleOptionClick(option)}>
avoid using index as key, learn why we should not use index.

2024-05-10 05:55 UTC, Delwalt commented on src/components/select/search.css
> +.container-main-2 {
there are many classes like this one which Search.js is not using then those classes should not be here. This css file should only be responsible for having CSS for Search.js file.

2024-05-10 05:56 UTC, Delwalt commented
Select component should be completely separate, it should have its own css, logic in it no other so that we can use it anywhere we want, and move it as well by simply copying it. Make sure create your component that way.

2024-08-16 04:15 UTC, Mohitktater commented on public/index.html
> +    <!--
Resolved

2024-08-16 04:19 UTC, closed without merging