Component Reusablity
Mohitktater/react-select-1 pull request #2
Opened 2024-08-13 04:34 UTC by Mohitktater

Hello 
please check the code for select box reuse functionality

2024-08-14 10:02 UTC, Delwalt requested changes

2024-08-14 10:02 UTC, Delwalt commented on src/components/select/Search.js
why do we have a this file ? All logic of this file can inside the index file.

2024-08-16 04:19 UTC, Mohitktater commented on src/App.js
> +  const softwareOptions = [
Resolved

2024-08-16 04:20 UTC, Mohitktater commented on src/App.js
> +  const TeamOptions = [
Resolved

2024-08-16 04:20 UTC, Mohitktater commented on src/components/select/Search.js
>  export const SearchableSelect = ({ options, onSelect }) => {
Resolved

2024-08-16 04:20 UTC, Mohitktater commented on src/components/select/Search.js
Resolved

2024-08-16 04:20 UTC, Mohitktater commented on src/components/select/Search.js
>    const handleShowList = () => {
Resolved

2024-08-16 04:20 UTC, Mohitktater commented on src/App.js
> +  const handleSelectChangeSoftware = (Option) => {
Resolved

2024-08-16 10:37 UTC, closed without merging